// Generated by scripts/generate_openapi_types.py. Do not edit by hand.

export interface AllProvidersSyncResponse {
  results: Record<string, ProviderSyncResponse>
  total_discovered: number
  total_new: number
}

export interface AskRequest {
  question: string
  strategy_model?: string | null
  answer_model?: string | null
  final_answer_model?: string | null
  team_id?: string | null
}

export interface AskResponse {
  answer: string
  question: string
}

export interface AssetModel {
  file_path?: string | null
  url?: string | null
  external_source_name?: string | null
}

export interface AuditLogListResponse {
  items: AuditLogResponse[]
  limit: number
  offset: number
  total: number
}

export interface AuditLogResponse {
  id: string
  actor_id?: string | null
  actor_username?: string | null
  action: string
  target_type?: string | null
  target_id?: string | null
  metadata?: Record<string, unknown>
  ip_address?: string | null
  user_agent?: string | null
  created: string
}

export interface AuthStatusResponse {
  auth_enabled: boolean
  auth_method: string
  has_users: boolean
  message: string
}

export interface AutoAssignResult {
  assigned: Record<string, string>
  skipped: string[]
  missing: string[]
}

export interface Body_create_source_api_sources_post {
  type: string
  workspace_id?: string | null
  notebook_id?: string | null
  notebooks?: string | null
  url?: string | null
  file_path?: string | null
  content?: string | null
  title?: string | null
  transformations?: string | null
  embed?: string
  delete_source?: string
  async_processing?: string
  visibility?: string
  file?: string | null
}

export interface BuildContextRequest {
  notebook_id: string
  context_config: Record<string, unknown>
}

export interface BuildContextResponse {
  context: Record<string, unknown>
  token_count: number
  char_count: number
}

export interface BulkDeleteRequest {
  source_ids: string[]
}

export interface BulkDeleteResponse {
  total_requested: number
  deleted_count: number
  failed_count: number
  results: BulkDeleteResult[]
}

export interface BulkDeleteResult {
  source_id: string
  title: string
  deleted: boolean
  error?: string | null
}

export interface ChangePasswordRequest {
  old_password: string
  new_password: string
}

export interface ChangePasswordResponse {
  success: boolean
  message: string
}

export interface ChatMessage {
  id: string
  type: string
  content: string
  timestamp?: string | null
}

export interface ChatSessionResponse {
  id: string
  title: string
  notebook_id?: string | null
  created: string
  updated: string
  message_count?: number | null
  model_override?: string | null
  capabilities?: ResourceCapabilities
}

export interface ChatSessionWithMessagesResponse {
  id: string
  title: string
  notebook_id?: string | null
  created: string
  updated: string
  message_count?: number | null
  model_override?: string | null
  capabilities?: ResourceCapabilities
  messages?: ChatMessage[]
}

export interface CommandExecutionRequest {
  command: string
  app: string
  input: Record<string, unknown>
}

export interface CommandJobResponse {
  job_id: string
  command_id: string
  status: string
  message: string
}

export interface CommandJobStatusResponse {
  job_id: string
  command_id: string
  status: string
  result?: Record<string, unknown> | null
  error_message?: string | null
  created?: string | null
  updated?: string | null
  progress?: Record<string, unknown> | null
}

export interface ContextConfig {
  sources?: Record<string, string>
  notes?: Record<string, string>
}

export interface ContextIndicator {
  sources?: string[]
  insights?: string[]
  notes?: string[]
}

export interface ContextRequest {
  notebook_id: string
  context_config?: ContextConfig | null
}

export interface ContextResponse {
  notebook_id: string
  sources: Record<string, unknown>[]
  notes: Record<string, unknown>[]
  total_tokens?: number | null
}

export interface CreateCredentialRequest {
  name: string
  provider: string
  modalities?: string[]
  api_key?: string | null
  base_url?: string | null
  endpoint?: string | null
  api_version?: string | null
  endpoint_llm?: string | null
  endpoint_embedding?: string | null
  endpoint_stt?: string | null
  endpoint_tts?: string | null
  project?: string | null
  location?: string | null
  credentials_path?: string | null
}

export interface CreateSessionRequest {
  notebook_id: string
  title?: string | null
  model_override?: string | null
}

export interface CreateSourceChatSessionRequest {
  source_id: string
  title?: string | null
  model_override?: string | null
}

export interface CreateSourceInsightRequest {
  transformation_id: string
  model_id?: string | null
}

export interface CredentialDeleteResponse {
  message: string
  deleted_models?: number
}

export interface CredentialResponse {
  id: string
  name: string
  provider: string
  modalities: string[]
  base_url?: string | null
  endpoint?: string | null
  api_version?: string | null
  endpoint_llm?: string | null
  endpoint_embedding?: string | null
  endpoint_stt?: string | null
  endpoint_tts?: string | null
  project?: string | null
  location?: string | null
  credentials_path?: string | null
  has_api_key?: boolean
  created: string
  updated: string
  model_count?: number
}

export interface DefaultModelsResponse {
  default_chat_model?: string | null
  default_transformation_model?: string | null
  large_context_model?: string | null
  default_text_to_speech_model?: string | null
  default_speech_to_text_model?: string | null
  default_embedding_model?: string | null
  default_tools_model?: string | null
}

export interface DefaultPromptResponse {
  transformation_instructions: string
}

export interface DefaultPromptUpdate {
  transformation_instructions: string
}

export interface DeleteResponse {
  success: boolean
  message: string
}

export interface DiscoverModelsResponse {
  credential_id: string
  provider: string
  discovered: api__models__DiscoveredModelResponse[]
}

export interface EmbedRequest {
  item_id: string
  item_type: string
  async_processing?: boolean
}

export interface EmbedResponse {
  success: boolean
  message: string
  item_id: string
  item_type: string
  command_id?: string | null
}

export interface EpisodeProfileCreate {
  name: string
  description?: string
  speaker_config: string
  outline_llm?: string | null
  transcript_llm?: string | null
  language?: string | null
  default_briefing: string
  num_segments?: number
  outline_provider?: string | null
  outline_model?: string | null
  transcript_provider?: string | null
  transcript_model?: string | null
}

export interface EpisodeProfileResponse {
  id: string
  name: string
  description: string
  speaker_config: string
  outline_llm?: string | null
  transcript_llm?: string | null
  language?: string | null
  default_briefing: string
  num_segments: number
  outline_provider?: string | null
  outline_model?: string | null
  transcript_provider?: string | null
  transcript_model?: string | null
}

export interface ExecuteChatRequest {
  session_id: string
  message: string
  context: Record<string, unknown>
  model_override?: string | null
  enable_web_search?: boolean | null
}

export interface ExternalApiCommandResponse {
  command_id: string
  status?: string
  message: string
}

export interface ExternalApiConnectionCreate {
  name: string
  target_type?: 'source' | 'output'
  base_url: string
  api_key: string
  manifest?: Record<string, unknown> | null
  enabled?: boolean
  timeout_seconds?: number
}

export interface ExternalApiConnectionListResponse {
  items: ExternalApiConnectionResponse[]
}

export interface ExternalApiConnectionResponse {
  id: string
  name: string
  target_type?: 'source' | 'output'
  base_url: string
  manifest?: Record<string, unknown> | null
  enabled: boolean
  timeout_seconds: number
  api_key_configured: boolean
  created_by?: string | null
  created: string
  updated: string
}

export interface ExternalApiConnectionTestResponse {
  ok: boolean
  status: string
  manifest?: Record<string, unknown> | null
  health?: Record<string, unknown> | null
  message?: string | null
}

export interface ExternalApiFetchRequest {
  team_id: string
}

export interface ExternalApiSearchRequest {
  team_id: string
  query: string
  limit?: number
  notebook_id?: string | null
  filters?: Record<string, unknown>
}

export interface ExternalApiUsageItem {
  source_id: string
  source_name?: string | null
  operation: 'search' | 'fetch' | 'generate'
  month: string
  requests: number
  quota: number
}

export interface ExternalApiUsageResponse {
  team_id: string
  month: string
  items: ExternalApiUsageItem[]
}

export interface ExternalAvailableSourceListResponse {
  items: ExternalAvailableSourceResponse[]
}

export interface ExternalAvailableSourceResponse {
  id: string
  connection_id: string
  connection_name?: string | null
  name: string
  key: string
  description?: string | null
  capabilities?: 'search' | 'fetch' | 'output'[]
  config?: Record<string, unknown>
  enabled: boolean
  created_by?: string | null
  created: string
  updated: string
  grant_id: string
  team_id: string
  monthly_request_quota: number
  current_month_usage?: number
}

export interface ExternalItemNotebookReferenceRequest {
  notebook_id: string
}

export interface ExternalItemSnapshotRequest {
  notebook_id: string
  embed?: boolean
}

export interface ExternalItemSnapshotResponse {
  item_id: string
  source_id: string
  notebook_id: string
  lumina_source: SourceResponse
}

export interface ExternalOutputGenerateRequest {
  team_id: string
  source_id: string
  prompt: string
  input_text?: string | null
  item_ids?: string[]
  output_kind?: 'markdown' | 'json' | 'file' | 'url'
  options?: Record<string, unknown>
}

export interface ExternalSourceCreate {
  connection_id: string
  name: string
  key: string
  description?: string | null
  capabilities?: 'search' | 'fetch' | 'output'[]
  config?: Record<string, unknown>
  enabled?: boolean
}

export interface ExternalSourceItemResponse {
  id: string
  source_id: string
  team_id: string
  external_id: string
  title: string
  summary?: string | null
  content_markdown?: string | null
  url?: string | null
  authors?: string[]
  published_at?: string | null
  metadata?: Record<string, unknown>
  fetched_at?: string | null
  created: string
  updated: string
}

export interface ExternalSourceListResponse {
  items: ExternalSourceResponse[]
}

export interface ExternalSourceResponse {
  id: string
  connection_id: string
  connection_name?: string | null
  name: string
  key: string
  description?: string | null
  capabilities?: 'search' | 'fetch' | 'output'[]
  config?: Record<string, unknown>
  enabled: boolean
  created_by?: string | null
  created: string
  updated: string
}

export interface ExternalSourceTeamGrantCreate {
  team_id: string
  monthly_request_quota: number
  enabled?: boolean
}

export interface ExternalSourceTeamGrantResponse {
  id: string
  source_id: string
  source_name?: string | null
  team_id: string
  team_name?: string | null
  monthly_request_quota: number
  enabled: boolean
  created_by?: string | null
  created: string
  updated: string
}

export interface ExternalSourceTeamGrantUpdate {
  monthly_request_quota?: number | null
  enabled?: boolean | null
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface InsightCreationResponse {
  status?: 'pending'
  message?: string
  source_id: string
  transformation_id: string
  command_id?: string | null
}

export interface LanguageResponse {
  code: string
  name: string
}

export interface LoginRequest {
  username: string
  password: string
}

export interface LoginResponse {
  success: boolean
  token?: string | null
  username?: string | null
  message?: string | null
}

export interface ModelCreate {
  name: string
  provider: string
  type: string
  credential?: string | null
}

export interface ModelResponse {
  id: string
  name: string
  provider: string
  type: string
  credential?: string | null
  created: string
  updated: string
}

export interface ModelTestResponse {
  success: boolean
  message: string
  details?: string | null
}

export interface NoteCreate {
  title?: string | null
  content: string
  note_type?: string | null
  notebook_id?: string | null
}

export interface NoteResponse {
  id: string
  title: string | null
  content: string | null
  note_type: string | null
  created: string
  updated: string
  command_id?: string | null
  owner_id?: string | null
  workspace_id?: string | null
  capabilities?: ResourceCapabilities
}

export interface NoteUpdate {
  title?: string | null
  content?: string | null
  note_type?: string | null
}

export interface NotebookCreate {
  name: string
  description?: string
  password?: string | null
  creator_name?: string | null
  workspace_id?: string | null
  visibility?: 'private' | 'public'
}

export interface NotebookDeletePreview {
  notebook_id: string
  notebook_name: string
  note_count: number
  exclusive_source_count: number
  shared_source_count: number
}

export interface NotebookDeleteResponse {
  message: string
  deleted_notes: number
  deleted_sources: number
  unlinked_sources: number
}

export interface NotebookResponse {
  id: string
  name: string
  description: string
  archived: boolean
  created: string
  updated: string
  source_count: number
  note_count: number
  view_count?: number
  reference_count?: number
  password?: string | null
  creator_name?: string | null
  creator_username?: string | null
  owner_id?: string | null
  workspace_id?: string | null
  visibility?: 'private' | 'team' | 'public'
  capabilities?: ResourceCapabilities
}

export interface NotebookUpdate {
  name?: string | null
  description?: string | null
  archived?: boolean | null
  password?: string | null
  creator_name?: string | null
  visibility?: 'private' | 'public' | null
}

export interface PodcastEpisodeResponse {
  id: string
  name: string
  episode_profile: Record<string, unknown>
  speaker_profile: Record<string, unknown>
  briefing: string
  audio_file?: string | null
  audio_url?: string | null
  transcript?: Record<string, unknown> | null
  outline?: Record<string, unknown> | null
  created?: string | null
  job_status?: string | null
  error_message?: string | null
}

export interface PodcastGenerationRequest {
  episode_profile: string
  speaker_profile: string
  episode_name: string
  content?: string | null
  notebook_id?: string | null
  briefing_suffix?: string | null
}

export interface PodcastGenerationResponse {
  job_id: string
  status: string
  message: string
  episode_profile: string
  episode_name: string
}

export interface ProfileUpdateRequest {
  display_name?: string | null
  locale?: string | null
  theme?: string | null
}

export interface ProviderAvailabilityResponse {
  available: string[]
  unavailable: string[]
  supported_types: Record<string, string[]>
}

export interface ProviderModelCountResponse {
  provider: string
  counts: Record<string, number>
  total: number
}

export interface ProviderSyncResponse {
  provider: string
  discovered: number
  new: number
  existing: number
}

export interface RebuildProgress {
  processed: number
  total: number
  percentage: number
}

export interface RebuildRequest {
  mode: 'existing' | 'all'
  include_sources?: boolean
  include_notes?: boolean
  include_insights?: boolean
}

export interface RebuildResponse {
  command_id: string
  total_items: number
  message: string
}

export interface RebuildStats {
  sources?: number
  notes?: number
  insights?: number
  failed?: number
}

export interface RebuildStatusResponse {
  command_id: string
  status: string
  progress?: RebuildProgress | null
  stats?: RebuildStats | null
  started_at?: string | null
  completed_at?: string | null
  error_message?: string | null
}

export interface RegisterModelData {
  name: string
  provider: string
  model_type: string
}

export interface RegisterModelsRequest {
  models: RegisterModelData[]
}

export interface RegisterModelsResponse {
  created: number
  existing: number
}

export interface RegisterRequest {
  email: string
  code: string
  password: string
  language?: 'en' | 'zh-CN'
}

export interface RegisterResponse {
  success: boolean
  message: string
  username?: string | null
}

export interface ResetPasswordRequest {
  email: string
  code: string
  new_password: string
  language?: 'en' | 'zh-CN'
}

export interface ResetPasswordResponse {
  success: boolean
  message: string
}

export interface ResetUserPasswordResponse {
  success: boolean
  temporary_password: string
  message: string
}

export interface ResourceCapabilities {
  can_read?: boolean
  can_update?: boolean
  can_delete?: boolean
  can_share?: boolean
  can_manage?: boolean
  can_create_source?: boolean
  can_remove_source?: boolean
  can_create_note?: boolean
  can_process?: boolean
}

export interface SaveAsNoteRequest {
  notebook_id?: string | null
}

export interface SearchRequest {
  query: string
  type?: 'text' | 'vector'
  limit?: number
  search_sources?: boolean
  search_notes?: boolean
  team_id?: string | null
  minimum_score?: number
}

export interface SearchResponse {
  results: Record<string, unknown>[]
  total_count: number
  search_type: string
}

export interface SendCodeRequest {
  email: string
  purpose: 'register' | 'reset_password'
  language?: 'en' | 'zh-CN'
}

export interface SendCodeResponse {
  success: boolean
  message: string
  expires_in_seconds?: number
}

export interface SendMessageRequest {
  message: string
  model_override?: string | null
  enable_web_search?: boolean | null
}

export interface SettingsResponse {
  default_content_processing_engine_doc?: 'auto' | 'docling' | 'mineru' | 'markitdown' | 'simple' | null
  default_content_processing_engine_url?: 'auto' | 'firecrawl' | 'jina' | 'simple' | null
  default_embedding_option?: 'ask' | 'always' | 'never' | null
  auto_delete_files?: 'yes' | 'no' | null
  youtube_preferred_languages?: string[] | null
  tavily_api_key?: string | null
  tavily_include_domains?: string | null
}

export interface SettingsUpdate {
  default_content_processing_engine_doc?: 'auto' | 'docling' | 'mineru' | 'markitdown' | 'simple' | null
  default_content_processing_engine_url?: 'auto' | 'firecrawl' | 'jina' | 'simple' | null
  default_embedding_option?: 'ask' | 'always' | 'never' | null
  auto_delete_files?: 'yes' | 'no' | null
  youtube_preferred_languages?: string[] | null
  tavily_api_key?: string | null
  tavily_include_domains?: string | null
}

export interface SetupRequest {
  username: string
  password: string
}

export interface ShareGrantCreateRequest {
  resource_type: 'source' | 'notebook'
  resource_id: string
  target_type: 'user' | 'team'
  target_id: string
  permission?: 'read'
}

export interface ShareGrantResponse {
  id: string
  resource_type: 'source' | 'notebook'
  resource_id: string
  target_type: 'user' | 'team'
  target_id: string
  permission: string
  created_by?: string | null
  created: string
}

export interface SourceChatSessionResponse {
  id: string
  title: string
  source_id: string
  model_override?: string | null
  created: string
  updated: string
  message_count?: number | null
  capabilities?: ResourceCapabilities
}

export interface SourceChatSessionWithMessagesResponse {
  id: string
  title: string
  source_id: string
  model_override?: string | null
  created: string
  updated: string
  message_count?: number | null
  capabilities?: ResourceCapabilities
  messages?: ChatMessage[]
  context_indicators?: ContextIndicator | null
}

export interface SourceInsightResponse {
  id: string
  source_id: string
  insight_type: string
  content: string
  created: string
  updated: string
}

export interface SourceListResponse {
  id: string
  title: string | null
  topics: string[] | null
  asset: AssetModel | null
  embedded: boolean
  embedded_chunks: number
  kg_extracted?: boolean
  insights_count: number
  reference_count: number
  view_count?: number
  created: string
  updated: string
  file_available?: boolean | null
  command_id?: string | null
  status?: string | null
  processing_info?: Record<string, unknown> | null
  owner_id?: string | null
  creator_username?: string | null
  workspace_id?: string | null
  visibility?: 'private' | 'team' | 'public'
  capabilities?: ResourceCapabilities
}

export interface SourceResponse {
  id: string
  title: string | null
  topics: string[] | null
  asset: AssetModel | null
  full_text: string | null
  embedded: boolean
  embedded_chunks: number
  kg_extracted?: boolean
  file_available?: boolean | null
  view_count?: number
  created: string
  updated: string
  command_id?: string | null
  status?: string | null
  processing_info?: Record<string, unknown> | null
  notebooks?: string[] | null
  owner_id?: string | null
  workspace_id?: string | null
  visibility?: 'private' | 'team' | 'public'
  capabilities?: ResourceCapabilities
}

export interface SourceStatusResponse {
  status?: string | null
  message: string
  processing_info?: Record<string, unknown> | null
  command_id?: string | null
}

export interface SourceUpdate {
  title?: string | null
  topics?: string[] | null
  visibility?: 'private' | 'public' | null
}

export interface SpeakerProfileCreate {
  name: string
  description?: string
  voice_model?: string | null
  speakers: Record<string, unknown>[]
  tts_provider?: string | null
  tts_model?: string | null
}

export interface SpeakerProfileResponse {
  id: string
  name: string
  description: string
  voice_model?: string | null
  speakers: Record<string, unknown>[]
  tts_provider?: string | null
  tts_model?: string | null
}

export interface SuccessResponse {
  success?: boolean
  message: string
}

export interface TeamAssignableUserListResponse {
  items: TeamMemberUser[]
  total: number
  limit: number
  offset: number
}

export interface TeamCreateRequest {
  name: string
  owner_id: string
  slug?: string | null
}

export interface TeamListResponse {
  items: TeamResponse[]
  total: number
  limit: number
  offset: number
}

export interface TeamMemberResponse {
  id: string
  team: string
  user: string
  user_info?: TeamMemberUser | null
  role: 'owner' | 'admin' | 'member' | 'viewer'
  status: 'active' | 'invited' | 'disabled'
  created: string
  updated?: string | null
}

export interface TeamMemberUpsertRequest {
  user_id: string
  role?: 'owner' | 'admin' | 'member' | 'viewer'
  status?: 'active' | 'disabled'
}

export interface TeamMemberUser {
  id: string
  username: string
  display_name?: string | null
  email?: string | null
}

export interface TeamModelAllowlistResponse {
  team_id: string
  model_ids: string[]
  models: ModelResponse[]
}

export interface TeamModelAllowlistUpdateRequest {
  model_ids?: string[]
}

export interface TeamModelDefaultsResponse {
  default_chat_model?: string | null
  default_transformation_model?: string | null
  large_context_model?: string | null
  default_embedding_model?: string | null
  default_tools_model?: string | null
  team_id: string
}

export interface TeamModelDefaultsUpdateRequest {
  default_chat_model?: string | null
  default_transformation_model?: string | null
  large_context_model?: string | null
  default_embedding_model?: string | null
  default_tools_model?: string | null
}

export interface TeamResponse {
  id: string
  slug: string
  name: string
  type?: 'workspace' | 'system'
  created_by?: string | null
  created: string
  updated: string
  member_count?: number
  share_count?: number
  current_user_role?: 'owner' | 'admin' | 'member' | 'viewer' | null
  can_manage?: boolean
}

export interface TeamTransformationAllowlistResponse {
  team_id: string
  transformation_ids: string[]
  transformations: TransformationResponse[]
}

export interface TeamTransformationAllowlistUpdateRequest {
  transformation_ids?: string[]
}

export interface TeamUpdateRequest {
  name?: string | null
}

export interface TransformationCreate {
  name: string
  title: string
  description: string
  prompt: string
  apply_default?: boolean
}

export interface TransformationExecuteRequest {
  transformation_id: string
  input_text: string
  model_id: string
}

export interface TransformationExecuteResponse {
  output: string
  transformation_id: string
  model_id: string
}

export interface TransformationResponse {
  id: string
  name: string
  title: string
  description: string
  prompt: string
  apply_default: boolean
  created: string
  updated: string
}

export interface TransformationUpdate {
  name?: string | null
  title?: string | null
  description?: string | null
  prompt?: string | null
  apply_default?: boolean | null
}

export interface UpdateCredentialRequest {
  name?: string | null
  modalities?: string[] | null
  api_key?: string | null
  base_url?: string | null
  endpoint?: string | null
  api_version?: string | null
  endpoint_llm?: string | null
  endpoint_embedding?: string | null
  endpoint_stt?: string | null
  endpoint_tts?: string | null
  project?: string | null
  location?: string | null
  credentials_path?: string | null
}

export interface UpdateSessionRequest {
  title?: string | null
  model_override?: string | null
}

export interface UpdateSourceChatSessionRequest {
  title?: string | null
  model_override?: string | null
}

export interface UserCreateRequest {
  username: string
  email?: string | null
  display_name?: string | null
  role?: 'admin' | 'user'
  password?: string | null
}

export interface UserCreateResponse {
  id?: string | null
  username: string
  email?: string | null
  display_name?: string | null
  role?: 'admin' | 'user'
  status?: 'active' | 'disabled'
  locale?: string | null
  theme?: string | null
  created: string
  updated: string
  last_login_at?: string | null
  temporary_password?: string | null
}

export interface UserListItem {
  id: string
  username: string
  email?: string | null
  display_name?: string | null
  role: 'admin' | 'user'
  status: 'active' | 'disabled'
  created: string
  updated: string
  last_login_at?: string | null
  source_count?: number
  notebook_count?: number
}

export interface UserListResponse {
  items: UserListItem[]
  total: number
  limit: number
  offset: number
}

export interface UserResponse {
  id?: string | null
  username: string
  email?: string | null
  display_name?: string | null
  role?: 'admin' | 'user'
  status?: 'active' | 'disabled'
  locale?: string | null
  theme?: string | null
  created: string
  updated: string
  last_login_at?: string | null
}

export interface UserUpdateRequest {
  display_name?: string | null
  role?: 'admin' | 'user' | null
  status?: 'active' | 'disabled' | null
}

export interface ValidationError {
  loc: string | number[]
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}

export interface WorkspaceListResponse {
  items: WorkspaceResponse[]
  total: number
}

export interface WorkspacePermissionPolicy {
  member_can_read?: boolean
  member_can_create_source?: boolean
  member_can_update_own_source?: boolean
  member_can_process_own_source?: boolean
  member_can_delete_own_source?: boolean
  member_can_remove_source?: boolean
  member_can_create_note?: boolean
  member_can_update_own_note?: boolean
  member_can_delete_own_note?: boolean
  member_can_delete_chat?: boolean
  member_can_update_notebook?: boolean
}

export interface WorkspacePolicyResponse {
  workspace_id: string
  policy: WorkspacePermissionPolicy
  effective_policy: WorkspacePermissionPolicy
}

export interface WorkspaceResourceMoveRequest {
  resource_type: 'notebook'
  resource_id: string
  mode?: 'move'
}

export interface WorkspaceResourceMoveResponse {
  resource_type: string
  resource_id: string
  source_workspace_id?: string | null
  target_workspace_id: string
  mode?: 'move'
  message: string
}

export interface WorkspaceResponse {
  id: string
  name: string
  type?: 'personal' | 'team'
  owner_id?: string | null
  team_id?: string | null
  created_by?: string | null
  created: string
  updated: string
  current_user_role?: 'owner' | 'admin' | 'member' | 'viewer' | null
  can_manage?: boolean
}

export interface WorkspaceSystemPolicyResponse {
  policy: WorkspacePermissionPolicy
}

export interface api__models__DiscoveredModelResponse {
  name: string
  provider: string
  model_type?: string | null
  description?: string | null
}

export interface api__routers__models__DiscoveredModelResponse {
  name: string
  provider: string
  model_type: string
  description?: string | null
}
