"""Detailed WBS task descriptions for the commercialization schedule workbook."""

from __future__ import annotations

from datetime import date

# Status: Done | In Progress | Pending | Blocked
# Each task: same 19-field tuple as generate_wbs_excel.COLS

TASKS: list[tuple] = [
    (
        "0.0",
        "Phase 0 — R&D Diligence",
        "Commercialization R&D dossier",
        "Purpose: establish whether the upstream Open Notebook codebase can be sold commercially without a licence dead-end.\n"
        "Steps: (1) inventory core and dependency licences; (2) assess SurrealDB BSL 1.1 for embedded/commercial use vs migration cost; "
        "(3) scan provider terms for commercial restrictions; (4) write the R&D dossier and SurrealDB migration assessment so later WPs have evidence, not guesses.",
        "R&D dossier; SurrealDB migration assessment",
        "Done",
        "High",
        "—",
        24,
        3,
        24,
        100,
        "Engineering Lead",
        date(2026, 7, 14),
        date(2026, 7, 18),
        date(2026, 7, 18),
        "R&D dossier exists and informs the master plan",
        "Pre-coding foundation; not a feature work package",
        "docs/commercialization/*",
    ),
    (
        "0.1",
        "Phase 0 — R&D Diligence",
        "Master implementation plan authored",
        "Purpose: turn R&D conclusions into an executable program.\n"
        "Steps: (1) define WP0–WP8 with objectives, tasks, and acceptance criteria; (2) draw the hard dependency graph "
        "(auth before white-label and SharePoint); (3) set execution rules — one branch per WP, tests required, stop for human review; "
        "(4) publish the plan under docs/commercialization/.",
        "open-notebook-master-implementation-plan.md",
        "Done",
        "Critical",
        "0.0",
        16,
        2,
        16,
        100,
        "Engineering Lead",
        date(2026, 7, 18),
        date(2026, 7, 20),
        date(2026, 7, 20),
        "Plan covers Phases 1–8 mapped to WPs; one-branch-per-WP rules defined",
        "Plan text still cites v1.10.0; fork baseline is v1.14.0",
        "docs/commercialization/open-notebook-master-implementation-plan.md",
    ),
    (
        "1.0",
        "WP0 — Foundations",
        "WP0 kickoff & branch",
        "Purpose: open the foundations package cleanly so no feature work mixes into the baseline.\n"
        "Steps: (1) create branch wp-0-foundations from main; (2) confirm remotes; (3) read root and directory CLAUDE.md / AGENTS.md before editing.",
        "Branch wp-0-foundations",
        "Done",
        "Critical",
        "0.1",
        1,
        0.25,
        1,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Branch exists; no feature work mixed in",
        "",
        "PR #1",
    ),
    (
        "1.1",
        "WP0 — Foundations",
        "Fork hygiene: remotes + upstream-base tag",
        "Purpose: freeze the exact upstream commit we forked from so future merges and audits have a clear baseline.\n"
        "Steps: (1) confirm origin points at HariHaranDFX/open-notebook; (2) add upstream lfnovo/open-notebook; "
        "(3) tag the fork point as upstream-base; (4) document remotes in DEV_SETUP.md.",
        "git tag upstream-base; upstream remote",
        "Done",
        "Critical",
        "1.0",
        2,
        0.25,
        2,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "upstream-base tag exists; upstream remote configured",
        "Tagged at 30c7e2a / v1.14.0 (not v1.10.0)",
        "tag: upstream-base",
    ),
    (
        "1.2",
        "WP0 — Foundations",
        "Reproduce clean build & document DEV_SETUP",
        "Purpose: prove a new machine can stand up the stack without tribal knowledge.\n"
        "Steps: (1) install backend with uv and start the API; (2) start SurrealDB via compose; (3) start the worker; "
        "(4) install/build the frontend; (5) record exact Windows and Linux steps, known failures, and coverage baselines in docs/DEV_SETUP.md.",
        "docs/DEV_SETUP.md",
        "Done",
        "Critical",
        "1.1",
        8,
        1,
        10,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Clean build reproducible from DEV_SETUP on a fresh machine",
        "Later note: on Windows use 127.0.0.1 not localhost for SurrealDB",
        "docs/DEV_SETUP.md",
    ),
    (
        "1.3",
        "WP0 — Foundations",
        "Characterization tests — notebook CRUD",
        "Purpose: lock today’s notebook API behaviour so later auth/ownership work cannot silently break CRUD.\n"
        "Steps: write pytest characterization covering create, read, update, and delete of notebooks; treat failures as regressions unless the test is updated deliberately in the same change.",
        "tests/characterization/ (CRUD)",
        "Done",
        "High",
        "1.2",
        6,
        1,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "CRUD characterization tests exist and pass",
        "Intentional behaviour changes must update the test in the same commit",
        "tests/characterization/",
    ),
    (
        "1.4",
        "WP0 — Foundations",
        "Characterization tests — source ingestion",
        "Purpose: capture the real ingestion path (upload / URL / text → content-core → jobs) as a regression net.\n"
        "Steps: add characterization coverage for the critical source ingestion flows used in production; note gaps found during testing for later product work (not WP0 scope).",
        "tests/characterization/ (ingestion)",
        "Done",
        "High",
        "1.2",
        8,
        1,
        8,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Ingestion characterization tests pass",
        "Product gap noted later: uploaded .html/.json/.png limits",
        "tests/characterization/",
    ),
    (
        "1.5",
        "WP0 — Foundations",
        "Characterization tests — search (text + vector)",
        "Purpose: protect both keyword and vector/semantic search behaviour before commercial features change data access patterns.\n"
        "Steps: add fixed-fixture characterization for text search and vector search endpoints; keep fixtures stable so CI failures mean real drift.",
        "tests/characterization/ (search)",
        "Done",
        "High",
        "1.2",
        6,
        1,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Search characterization tests pass",
        "",
        "tests/characterization/",
    ),
    (
        "1.6",
        "WP0 — Foundations",
        "Characterization tests — chat",
        "Purpose: baseline the notebook chat / ask critical path so auth and model changes do not break the core product loop.\n"
        "Steps: add characterization for the chat path (provider calls mocked where needed); assert response shape and error handling match current behaviour.",
        "tests/characterization/ (chat)",
        "Done",
        "High",
        "1.2",
        6,
        1,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Chat characterization tests pass",
        "",
        "tests/characterization/",
    ),
    (
        "1.7",
        "WP0 — Foundations",
        "Coverage ratchet (backend + frontend)",
        "Purpose: stop coverage from silently declining as the commercial fork grows.\n"
        "Steps: enable coverage tooling; record baselines (backend ≥56%, frontend ≥35.79% statements); document that coverage may only increase.",
        "Coverage config + baseline in DEV_SETUP.md",
        "Done",
        "High",
        "1.3",
        4,
        0.5,
        4,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Baselines recorded; ratchet documented/enforced",
        "",
        "docs/DEV_SETUP.md",
    ),
    (
        "1.8",
        "WP0 — Foundations",
        "CI pipeline: lint, typecheck, tests, build",
        "Purpose: make every PR prove the fork still builds and tests before merge.\n"
        "Steps: configure GitHub Actions for Backend Tests / Lint / Typecheck and Frontend Tests / Lint / Build; require green checks before merge to main.",
        "CI workflow green on PR",
        "Done",
        "Critical",
        "1.7",
        8,
        1,
        8,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "CI runs on PR and blocks merge on failure",
        "Seven required checks including License Scan",
        "PR #1",
    ),
    (
        "1.9",
        "WP0 — Foundations",
        "License scan in CI (GPL/AGPL drift guard)",
        "Purpose: catch copyleft dependencies the moment they appear via a transitive update.\n"
        "Steps: implement scripts/check_licenses.py; wire the License Scan CI job; fail on non-allowlisted GPL; never allowlist AGPL; require a written justification for any allowlist entry.",
        "scripts/check_licenses.py + CI job",
        "Done",
        "Critical",
        "1.8",
        6,
        1,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "License scan runs in CI and passes",
        "Allowlist is a reviewed decision list, not a shortcut",
        "scripts/check_licenses.py",
    ),
    (
        "1.10",
        "WP0 — Foundations",
        "Branch protection on main",
        "Purpose: enforce the PR-only workflow even for admins.\n"
        "Steps: require the seven checks; require branch up to date with main; reject direct pushes; disable force-push and branch deletion; verify with a probe push.",
        "Protected main branch",
        "Done",
        "Critical",
        "1.8",
        2,
        0.25,
        2,
        100,
        "Maintainer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Direct push rejected; PRs required",
        "",
        "PR #2",
    ),
    (
        "1.11",
        "WP0 — Foundations",
        "WP0 close-out docs + human review",
        "Purpose: formally close foundations before licensing work starts.\n"
        "Steps: update status docs; merge remaining WP0 PR; confirm all five WP0 acceptance criteria; stop for human review before WP1.",
        "WP0 complete on main; PRs #1–#2",
        "Done",
        "High",
        "1.9,1.10",
        2,
        0.25,
        2,
        100,
        "Engineering Lead",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "All five WP0 acceptance criteria pass",
        "",
        "PR #2",
    ),
    (
        "2.0",
        "WP1 — Licensing & Compliance",
        "WP1 kickoff & branch",
        "Purpose: start licensing work on an isolated branch with the company legal name fixed.\n"
        "Steps: create wp-1-* branches as needed; use legal name DataFabricX Pvt Ltd; keep SurrealDB (already decided); exclude unrelated feature work.",
        "Branches wp-1-*",
        "Done",
        "Critical",
        "1.11",
        1,
        0.25,
        1,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "WP1-only scope",
        "",
        "PR #4",
    ),
    (
        "2.1",
        "WP1 — Licensing & Compliance",
        "Preserve attribution + add DataFabricX copyright",
        "Purpose: meet MIT attribution while asserting our commercial copyright.\n"
        "Steps: add a DataFabricX copyright block above Luis Novo’s retained MIT copyright in LICENSE; never replace or remove upstream copyright; ship LICENSE with the product.",
        "LICENSE updated",
        "Done",
        "Critical",
        "2.0",
        2,
        0.25,
        2,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "LICENSE retains upstream copyright + our copyright",
        "",
        "LICENSE; PR #4",
    ),
    (
        "2.2",
        "WP1 — Licensing & Compliance",
        "Purge asciidoc (GPLv2+) from shipped image",
        "Purpose: avoid distributing GPLv2+ in commercial images even when the library is unmodified.\n"
        "Why it matters: GPL obligations attach on distribution; Docker images are distribution. Unmodified use does not make GPLv2+ safe to ship.\n"
        "Steps: (1) purge asciidoc from the shipped image; (2) keep a reviewed allowlist entry for local/CI only; "
        "(3) open upstream content-core#58 to remove the dependency properly; (4) add a guard test; (5) when upstream merges and we bump, drop purge and allowlist together.",
        "Dockerfile purge; content-core#58; tests",
        "Done",
        "Critical",
        "2.0",
        8,
        1,
        10,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "No asciidoc in shipped image",
        "Follow-up 3.8 removes the temporary purge after upstream bump",
        "PR #3; lfnovo/content-core#58",
    ),
    (
        "2.3",
        "WP1 — Licensing & Compliance",
        "Generate THIRD-PARTY-NOTICES.md (Linux)",
        "Purpose: publish an accurate attribution list for every third-party component we distribute.\n"
        "Steps: auto-generate Python + frontend notices; fix bad/UNKNOWN fields (tiktoken licence text dump, caio/content-core); "
        "add SurrealDB BSL entry; require Linux generation; add CI drift detection so the file cannot go stale unnoticed.",
        "THIRD-PARTY-NOTICES.md; scripts/generate_notices.py",
        "Done",
        "Critical",
        "2.1,2.2",
        12,
        1.5,
        14,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Notices complete, reproducible, CI-guarded",
        "Must be regenerated on Linux",
        "PR #4",
    ),
    (
        "2.4",
        "WP1 — Licensing & Compliance",
        "pycountry unmodified integrity guard",
        "Purpose: keep LGPL-2.1 obligations at zero by never modifying or vendoring pycountry.\n"
        "Steps: document the rule in LICENSE_COMPLIANCE; add tests/test_pycountry_unmodified.py that hashes installed files against the package RECORD; fail CI if a byte changes.",
        "Integrity test + compliance docs",
        "Done",
        "High",
        "2.1",
        4,
        0.5,
        4,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "pycountry documented unmodified; CI asserts",
        "",
        "tests/test_pycountry_unmodified.py",
    ),
    (
        "2.5",
        "WP1 — Licensing & Compliance",
        "SurrealDB BSL: multi-container path documented",
        "Purpose: record why pulling the official SurrealDB image is not redistribution, and why we keep BSL.\n"
        "Steps: document the default compose path (official image as a dependency); record Additional Use Grant position for commercial embedding; cite the pinned SurrealDB version’s terms.",
        "LICENSE_COMPLIANCE.md SurrealDB section",
        "Done",
        "High",
        "2.3",
        3,
        0.5,
        3,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "BSL entry accurate for pinned SurrealDB version",
        "Business decision: keep SurrealDB (see LEGAL_DECISIONS)",
        "docs/LICENSE_COMPLIANCE.md",
    ),
    (
        "2.6",
        "WP1 — Licensing & Compliance",
        "Ship BSL text inside single-container image",
        "Purpose: when Dockerfile --target single copies the SurrealDB binary into our image, that is redistribution and the BSL text must travel with it.\n"
        "Steps: vendor licenses/SURREALDB-BSL-1.1.txt from the matching SurrealDB tag; COPY into /app/licenses/; verify inside a real built image; re-fetch if the pin changes.",
        "licenses/SURREALDB-BSL-1.1.txt + Dockerfile",
        "Done",
        "Critical",
        "2.5",
        6,
        1,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "BSL text present in single image filesystem",
        "Official SurrealDB image ships no licence file of its own",
        "PR #5",
    ),
    (
        "2.7",
        "WP1 — Licensing & Compliance",
        "PROVIDER_TERMS.md for all providers",
        "Purpose: ensure every provider the product can call has a reviewed commercial-terms pointer before sales.\n"
        "Steps: list all enabled providers (~22) with ToS links; flag PRC-jurisdiction providers, ElevenLabs commercial audio rights, and local model-weight licences for follow-through.",
        "docs/PROVIDER_TERMS.md",
        "Done",
        "High",
        "2.0",
        8,
        1,
        8,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "PROVIDER_TERMS.md exists for all providers",
        "Re-verify links before commercial launch (task 3.11)",
        "docs/PROVIDER_TERMS.md",
    ),
    (
        "2.8",
        "WP1 — Licensing & Compliance",
        "Encryption key handling documentation",
        "Purpose: prevent encryption keys from being committed or shared across deployments.\n"
        "Steps: document OPEN_NOTEBOOK_ENCRYPTION_KEY / _FILE — generate per deployment, never commit, rotation guidance — in LICENSE_COMPLIANCE.",
        "Encryption section in compliance docs",
        "Done",
        "High",
        "2.0",
        2,
        0.25,
        2,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "No secrets committed; key handling documented",
        "",
        "docs/LICENSE_COMPLIANCE.md",
    ),
    (
        "2.9",
        "WP1 — Licensing & Compliance",
        "LICENSE_COMPLIANCE.md standing rules",
        "Purpose: give every future dependency change a single binding rulebook.\n"
        "Steps: write standing rules (no GPL/AGPL; no PyMuPDF/poppler; pycountry unmodified; notices regeneration; brand inventory deferred to WP3).",
        "docs/LICENSE_COMPLIANCE.md",
        "Done",
        "High",
        "2.3,2.7",
        6,
        0.75,
        6,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Rules readable before any dependency add",
        "Rebranding correctly deferred to WP3",
        "docs/LICENSE_COMPLIANCE.md",
    ),
    (
        "2.10",
        "WP1 — Licensing & Compliance",
        "Legal decisions record (business accept/assign)",
        "Purpose: record DataFabricX business decisions on each WP1 risk — accept, assign to client, or fix in code — without pretending to be counsel advice.\n"
        "Steps: create LEGAL_DECISIONS.md covering SurrealDB keep, single-image BSL fix, PRC providers, ElevenLabs, local model weights, and customer-configured endpoints; list remaining ToS/product follow-through.",
        "docs/LEGAL_DECISIONS.md",
        "Done",
        "Critical",
        "2.5,2.7",
        6,
        0.75,
        6,
        100,
        "Product Owner + Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "Six items decided with conditions; engineering diligence recorded",
        "Customer ToS wording still outstanding (task 3.9)",
        "PR #5; docs/LEGAL_DECISIONS.md",
    ),
    (
        "2.11",
        "WP1 — Licensing & Compliance",
        "Windows test/docs hardening (WP1 follow-up)",
        "Purpose: make local Windows verification trustworthy for the team.\n"
        "Steps: fix make start-all issues; correct path/symlink test failures; document SURREAL_URL using 127.0.0.1 because localhost can hit an IPv6 stall and false “database offline” under a 2s health budget.",
        "DEV_SETUP updates; Windows test fixes",
        "Done",
        "Medium",
        "2.6",
        8,
        1,
        8,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 22),
        date(2026, 7, 22),
        "Documented Windows pitfalls; tests green where applicable",
        "Found during local verification of WP1",
        "PR #5",
    ),
    (
        "2.12",
        "WP1 — Licensing & Compliance",
        "WP1 merge + close-out",
        "Purpose: land licensing on main and free the critical path for tenancy decision + auth.\n"
        "Steps: merge PRs #3–#5; confirm WP1 acceptance criteria; stop for human review before WP2 feature work.",
        "WP1 on main",
        "Done",
        "Critical",
        "2.10,2.11",
        2,
        0.25,
        2,
        100,
        "Engineering Lead",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "All WP1 acceptance criteria met",
        "",
        "PRs #3,#4,#5",
    ),
    (
        "3.0",
        "WP-DEC — Multi-tenancy Decision",
        "Choose Model A vs Model B",
        "Purpose: pick the tenancy model before auth/theming/connectors are built (building the wrong model means rebuilding).\n"
        "Model A: one isolated instance per client (physical separation). Model B: one instance, many clients, tenant_id on every row.\n"
        "Decision: Model A for first commercial release — isolation is architectural, matches per-client install/branding, lower eng cost; revisit if ops cost or self-serve free tier forces multi-tenant.",
        "Decision recorded",
        "Done",
        "Critical",
        "2.12",
        4,
        0.5,
        4,
        100,
        "Product Owner",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "ONE model chosen and documented before WP2",
        "Approved by DataFabricX 2026-07-21",
        "docs/TENANCY.md",
    ),
    (
        "3.1",
        "WP-DEC — Multi-tenancy Decision",
        "Document TENANCY.md consequences",
        "Purpose: make the Model A choice binding for downstream packages.\n"
        "Steps: document implications for WP2 (user_id + client_id), WP3 (brand at startup), WP5 (per-user tokens), WP7 (installer = one instance); list revisit triggers; note LEGAL_DECISIONS depends on client-operated instances.",
        "docs/TENANCY.md",
        "Done",
        "Critical",
        "3.0",
        3,
        0.5,
        3,
        100,
        "Engineer",
        date(2026, 7, 21),
        date(2026, 7, 21),
        date(2026, 7, 21),
        "TENANCY.md accepted; WP2/3/5/7 assume Model A",
        "If DataFabricX hosts instances or supplies provider keys, reopen with LEGAL_DECISIONS",
        "docs/TENANCY.md",
    ),
    (
        "3.4",
        "Carry-forward / Tech Debt",
        "Adopt esperanto 2.26.0 (Azure STT verbose_json fix)",
        "Purpose: pull the upstream fix for Azure gpt-4o-*-transcribe failures caused by hardcoded response_format=verbose_json.\n"
        "Filed as lfnovo/esperanto#263; fixed in esperanto PR #270 and released in v2.26.0.\n"
        "Steps: bump floor to >=2.26.0; refresh lock + notices; keep our PR #6 nested STT config (still required — AzureSpeechToTextModel remains a dataclass that only reads nested config).",
        "App on esperanto >=2.26.0; Azure non-Whisper STT format resolved upstream",
        "Done",
        "High",
        "2.12",
        2,
        0.25,
        2,
        100,
        "Engineer",
        date(2026, 7, 30),
        date(2026, 7, 30),
        date(2026, 7, 30),
        "Locked to esperanto 2.26.0; _resolve_transcription_response_format used by Azure STT",
        "No local verbose_json workaround existed; PR #6 nesting kept on purpose",
        "https://github.com/lfnovo/esperanto/issues/263 · v2.26.0",
    ),
    (
        "3.5",
        "Carry-forward / Tech Debt",
        "Azure credential form: api_version field",
        "Purpose: fix a product bug found during WP1 local testing — Azure OpenAI requires an API version, but the credential form has no field for it.\n"
        "Impact: embeddings, transformations, and chat fail when api_version is null even if key and endpoint are set.\n"
        "Steps: add api_version to CredentialFormDialog and persistence; verify connection + real inference; keep separate from WP2 scope.",
        "Working Azure credential UI",
        "Pending",
        "High",
        "2.12",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 8, 4),
        date(2026, 8, 5),
        None,
        "User can set api_version in UI; connection + inference succeed",
        "PR #6 nested STT config kept; esperanto#263 transcription format fixed via task 3.4",
        "Bug found 2026-07-22",
    ),
    (
        "3.6",
        "Carry-forward / Tech Debt",
        "Upstream Azure GA API support in esperanto",
        "Purpose: track the library gap where Azure’s newer GA surface still is not fully usable from this app without an api-version query parameter.\n"
        "Steps: follow esperanto#262; adopt the upstream fix when available or keep documenting the supported preview/api-version pins; do not block WP2 on this.",
        "Upstream fix or documented workaround",
        "Pending",
        "Medium",
        "3.5",
        4,
        0.5,
        None,
        0,
        "Engineer",
        date(2026, 8, 4),
        date(2026, 8, 8),
        None,
        "Connection/inference path documented and stable for supported versions",
        "Filed as lfnovo/esperanto#262 — still open (separate from #263 / task 3.4)",
        "https://github.com/lfnovo/esperanto/issues/262",
    ),
    (
        "3.7",
        "Carry-forward / Tech Debt",
        "Upload support for .html / .json / .png",
        "Purpose: close extraction gaps found while testing — uploaded .html is rejected (inline HTML works), and .json/.png need Docling or pipeline work.\n"
        "Steps: decide supported matrix; implement or document clearly; optionally fold into WP5/WP6 rather than a one-off.",
        "Supported upload types documented + implemented as needed",
        "Pending",
        "Medium",
        "1.4",
        16,
        2,
        None,
        0,
        "Engineer",
        date(2026, 8, 11),
        date(2026, 8, 13),
        None,
        "Documented types work via the upload path",
        "Product gap, not a licensing issue",
        "Noted in CLAUDE.md",
    ),
    (
        "3.8",
        "Carry-forward / Tech Debt",
        "Drop asciidoc purge after content-core bump",
        "Purpose: remove the temporary Dockerfile purge once upstream stops pulling asciidoc.\n"
        "Blocked on: lfnovo/content-core#58 merge + dependency bump here.\n"
        "Steps: bump content-core; delete purge; remove allowlist entry in the same change; confirm License Scan still green.",
        "Cleaner image; allowlist reduced",
        "Blocked",
        "Low",
        "2.2",
        2,
        0.25,
        None,
        0,
        "Engineer",
        None,
        None,
        None,
        "asciidoc gone from allowlist and Dockerfile",
        "Blocked on upstream PR",
        "content-core#58",
    ),
    (
        "3.9",
        "Carry-forward / Legal Follow-through",
        "Customer ToS wording (model weights & endpoints)",
        "Purpose: make the LEGAL_DECISIONS assignments to the client enforceable in a document the customer actually signs.\n"
        "Why it matters: you decided that local model-weight licences (Ollama/oMLX) and customer-configured OpenAI/Anthropic-compatible endpoints are the client’s responsibility. "
        "That assignment only holds if the customer agrees in writing; an internal decision file is not enough.\n"
        "Steps: (1) draft ToS clauses for items 5–6 (and ideally item 3 / PRC providers); (2) legal/product review; (3) include in customer paperwork before commercial launch.\n"
        "Not an engineering blocker for WP2; it is a commercial-launch gate.",
        "Customer ToS draft sections",
        "Pending",
        "High",
        "2.10,3.1",
        8,
        1,
        None,
        0,
        "Legal / Product",
        date(2026, 8, 4),
        date(2026, 8, 8),
        None,
        "Customer has written agreement covering the assignments",
        "Blocks launch paperwork, not WP2 coding",
        "docs/LEGAL_DECISIONS.md",
    ),
    (
        "3.10",
        "Carry-forward / Legal Follow-through",
        "PRC providers opt-in (not default)",
        "Purpose: make “client chooses PRC-jurisdiction providers” a real choice, not a silent default.\n"
        "Providers: DeepSeek, DashScope (Qwen), MiniMax.\n"
        "Why it matters: LEGAL_DECISIONS assigns residency risk to the client only if the client enables those providers deliberately. "
        "If they are on by default, research content can be routed to a PRC jurisdiction without an explicit decision.\n"
        "Steps: (1) default those providers off per deployment; (2) require explicit enable; (3) UI copy stating data-residency implication at enable time. "
        "Track during WP2/WP3 provider-configuration UI work.",
        "Opt-in provider config + UI copy",
        "Pending",
        "High",
        "2.10",
        12,
        1.5,
        None,
        0,
        "Engineer",
        date(2026, 8, 18),
        date(2026, 8, 20),
        None,
        "PRC providers off by default; enabling requires explicit choice with residency notice",
        "LEGAL_DECISIONS item 3 outstanding product action",
        "LEGAL_DECISIONS item 3",
    ),
    (
        "3.11",
        "Carry-forward / Legal Follow-through",
        "Re-verify PROVIDER_TERMS links pre-launch",
        "Purpose: ensure every commercial ToS link in PROVIDER_TERMS.md is still live and still matches what we claim before launch.\n"
        "Why it matters: providers change terms and URLs without notice; a stale link is a compliance gap at the moment you sell.\n"
        "Steps: walk every entry; fix dead/moved URLs; note material term changes for product/legal; schedule as a launch checklist item.",
        "Updated PROVIDER_TERMS.md",
        "Pending",
        "Medium",
        "2.7",
        4,
        0.5,
        None,
        0,
        "Legal / Engineer",
        None,
        None,
        None,
        "All links live; terms still accurately summarised",
        "Launch gate; repeatable checklist",
        "docs/PROVIDER_TERMS.md",
    ),
    (
        "4.0",
        "WP2 — Identity & Entra Auth",
        "WP2 kickoff: branch + spike",
        "Purpose: open the identity package and lock Entra prerequisites before coding middleware.\n"
        "Steps: (1) create branch wp-2-entra-auth; (2) spike Entra app registration (redirect URIs, API permissions, admin consent); "
        "(3) confirm Model A assumptions from TENANCY.md; (4) re-read WP2 design in the master plan; (5) list env vars and local password-fallback behaviour.\n"
        "This is the program critical-path start: white-label (WP3) and SharePoint connectors (WP5) both need real users/tokens.",
        "Branch + spike notes / Entra checklist",
        "In Progress",
        "Critical",
        "3.1",
        4,
        0.5,
        None,
        15,
        "Engineer",
        date(2026, 8, 1),
        date(2026, 8, 1),
        None,
        "Branch ready; Entra app registration checklist drafted",
        "Current work package kickoff",
        "Plan WP2; CLAUDE.md current WP = WP2",
    ),
    (
        "4.1",
        "WP2 — Identity & Entra Auth",
        "Backend AuthProvider abstraction",
        "Purpose: stop hard-wiring password auth so Entra (and later other IdPs) plug in without rewriting every route.\n"
        "Steps: create api/auth/ with an AuthProvider protocol; move existing password logic into PasswordAuthProvider; select provider via config; keep password mode as local-dev fallback.",
        "api/auth/ + PasswordAuthProvider",
        "Pending",
        "Critical",
        "4.0",
        12,
        1.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 1),
        date(2026, 8, 4),
        None,
        "Password provider still works as local-dev fallback behind a flag",
        "Preserve existing password behaviour for tests",
        "",
    ),
    (
        "4.2",
        "WP2 — Identity & Entra Auth",
        "EntraOIDCProvider — JWT validation",
        "Purpose: validate real Microsoft Entra tokens on the API — issuer, audience, signature (JWKS), expiry, and claims.\n"
        "Steps: implement EntraOIDCProvider; configure ENTRA_TENANT_ID, ENTRA_CLIENT_ID, ENTRA_CLIENT_SECRET, ENTRA_REDIRECT_URI, AUTH_PROVIDER=entra; reject invalid tokens with clear 401s.",
        "EntraOIDCProvider",
        "Pending",
        "Critical",
        "4.1",
        20,
        2.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 4),
        date(2026, 8, 7),
        None,
        "API accepts valid Entra JWTs and rejects invalid/expired ones",
        "Use maintained JWT/JWKS libraries",
        "",
    ),
    (
        "4.3",
        "WP2 — Identity & Entra Auth",
        "AuthMiddleware + request user context",
        "Purpose: replace the single shared-password middleware with provider-delegating middleware that attaches the resolved user (and client_id) to each request.\n"
        "Steps: swap PasswordAuthMiddleware for AuthMiddleware; populate request context; ensure unauthenticated calls fail closed in entra mode.",
        "AuthMiddleware",
        "Pending",
        "Critical",
        "4.2",
        12,
        1.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 7),
        date(2026, 8, 8),
        None,
        "Every protected API request validates a real Entra token when entra mode is on",
        "",
        "",
    ),
    (
        "4.4",
        "WP2 — Identity & Entra Auth",
        "User model + SurrealDB migration + JIT provision",
        "Purpose: create a real user record on first successful login (no pre-provisioning required).\n"
        "Steps: add user model (id, email, display name, Entra oid/sub, client_id, role); add migration N.surrealql and AsyncMigrationManager entry; create-or-update on login.",
        "user model + migration",
        "Pending",
        "Critical",
        "4.3",
        16,
        2,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 8),
        date(2026, 8, 11),
        None,
        "User record exists after first successful login",
        "Migrations are hard-coded, not auto-discovered",
        "",
    ),
    (
        "4.5",
        "WP2 — Identity & Entra Auth",
        "Roles & authorization on sensitive routes",
        "Purpose: stop every logged-in user from changing models, credentials, and rebuild settings.\n"
        "Steps: define at least admin and user roles; enforce 403 on settings, models, credentials, embedding rebuild, and other sensitive routes.",
        "RBAC checks on sensitive routers",
        "Pending",
        "High",
        "4.4",
        12,
        1.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 11),
        date(2026, 8, 12),
        None,
        "Unauthorized callers receive 403 on sensitive routes",
        "",
        "",
    ),
    (
        "4.6",
        "WP2 — Identity & Entra Auth",
        "Data ownership: user_id (+ client_id) on notebooks/sources",
        "Purpose: move from “all data is global to the instance” to per-user ownership while keeping Model A simple.\n"
        "Steps: add user_id and client_id (constant per deployment under Model A, kept for a future Model B); filter create/read paths; update characterization tests deliberately where behaviour changes.\n"
        "Risk: this is the largest WP2 surface area — missing filters leak another user’s notebooks.",
        "Schema + query ownership filters",
        "Pending",
        "Critical",
        "4.4",
        24,
        3,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 12),
        date(2026, 8, 15),
        None,
        "Users only see their own notebooks/sources",
        "Highest-risk WP2 task",
        "",
    ),
    (
        "4.7",
        "WP2 — Identity & Entra Auth",
        "Frontend Entra login (OIDC + PKCE)",
        "Purpose: replace the shared-password login UI with Entra Authorization Code + PKCE.\n"
        "Steps: implement redirect/callback in LoginForm/auth-store; prefer httpOnly cookies over localStorage; silent refresh; logout clears Entra session; guard dashboard routes; CSRF protection if cookie-based.",
        "Entra login UX + session handling",
        "Pending",
        "Critical",
        "4.3",
        24,
        3,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 8),
        date(2026, 8, 13),
        None,
        "Login via a real Entra account works end-to-end",
        "",
        "",
    ),
    (
        "4.8",
        "WP2 — Identity & Entra Auth",
        "Stub GenericOIDCProvider (pluggability proof)",
        "Purpose: prove a second identity provider can be added without touching route handlers.\n"
        "Steps: add a minimal GenericOIDCProvider stub and a test demonstrating handlers stay provider-agnostic; SAML remains a later optional extension.",
        "GenericOIDCProvider stub + test",
        "Pending",
        "Medium",
        "4.1,4.3",
        8,
        1,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 13),
        date(2026, 8, 14),
        None,
        "Adding a second provider requires no change to route handlers",
        "",
        "",
    ),
    (
        "4.9",
        "WP2 — Identity & Entra Auth",
        "docs/AUTH.md",
        "Purpose: give operators a complete Entra setup and extension guide.\n"
        "Steps: document app registration, redirect URIs, API permissions, admin consent, env config, password fallback, and how to add another provider.",
        "docs/AUTH.md",
        "Pending",
        "High",
        "4.7,4.8",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 8, 14),
        date(2026, 8, 15),
        None,
        "AUTH.md complete for operators",
        "",
        "",
    ),
    (
        "4.10",
        "WP2 — Identity & Entra Auth",
        "WP2 tests, CI green, human review stop",
        "Purpose: close WP2 only when acceptance criteria and CI are green, then stop for human review (do not start WP3 on the same branch).\n"
        "Steps: unit/integration/E2E for auth; intentional characterization updates; open PR; merge only when all WP2 criteria pass.",
        "Green PR wp-2-entra-auth",
        "Pending",
        "Critical",
        "4.5,4.6,4.7,4.9",
        16,
        2,
        None,
        0,
        "Engineer",
        date(2026, 8, 15),
        date(2026, 8, 18),
        None,
        "All WP2 acceptance criteria pass; CI green",
        "Largest single change in the program",
        "",
    ),
    (
        "5.0",
        "WP3 — Frontend Map + White-label",
        "WP3 kickoff",
        "Purpose: start white-label work only after identity is on main.\n"
        "Steps: create wp-3-white-label; confirm Model A brand loads once at app startup (not per request).",
        "Branch",
        "Pending",
        "High",
        "4.10",
        1,
        0.25,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 19),
        date(2026, 8, 19),
        None,
        "Branch created after WP2 merge",
        "Optional admin brand UI needs WP2 roles",
        "",
    ),
    (
        "5.1",
        "WP3 — Frontend Map + White-label",
        "Produce docs/FRONTEND_MAP.md",
        "Purpose: make every future UI change locatable without archaeology.\n"
        "Steps: for each auth and dashboard route, document page → component tree, stores/hooks/API calls, shared layout, component catalog, and a where-do-I-change-X table.",
        "docs/FRONTEND_MAP.md",
        "Pending",
        "High",
        "5.0",
        20,
        2.5,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 19),
        date(2026, 8, 21),
        None,
        "Map covers every route with data flow + backend calls",
        "",
        "",
    ),
    (
        "5.2",
        "WP3 — Frontend Map + White-label",
        "BrandConfig schema + loader",
        "Purpose: drive app name, logos, favicon, colours, font, and support URL from config so clients do not need a rebuild.\n"
        "Steps: define BrandConfig schema; load from BRAND_CONFIG_PATH or /config/brand at startup under Model A.",
        "BrandConfig type + loader",
        "Pending",
        "Critical",
        "5.0",
        12,
        1.5,
        None,
        0,
        "Full-stack",
        date(2026, 8, 21),
        date(2026, 8, 22),
        None,
        "Config loads without a rebuild",
        "",
        "",
    ),
    (
        "5.3",
        "WP3 — Frontend Map + White-label",
        "Runtime theme injection (CSS variables)",
        "Purpose: apply BrandConfig at runtime to CSS variables for light and dark themes.\n"
        "Steps: map colours to :root / dark variants; replace hardcoded title and /logo.svg; use the brand inventory in LICENSE_COMPLIANCE §8; demonstrate two brands from one build.",
        "Runtime theming",
        "Pending",
        "Critical",
        "5.2",
        16,
        2,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 22),
        date(2026, 8, 25),
        None,
        "Two visibly different brands from the same build; no code edit to rebrand",
        "",
        "",
    ),
    (
        "5.4",
        "WP3 — Frontend Map + White-label",
        "themes/ presets + add-client procedure",
        "Purpose: make “add a client theme” a documented drop-in of config + assets.\n"
        "Steps: ship at least two presets under themes/; write the operator procedure (no rebuild).",
        "themes/ + docs procedure",
        "Pending",
        "High",
        "5.3",
        8,
        1,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 25),
        date(2026, 8, 26),
        None,
        "Documented procedure produces two different brands from one build",
        "",
        "",
    ),
    (
        "5.5",
        "WP3 — Frontend Map + White-label",
        "Optional admin BrandConfig UI",
        "Purpose (optional): let admins edit BrandConfig live without redeploying.\n"
        "Steps: admin-only settings screen gated by WP2 roles; persist and hot-apply theme.",
        "Admin brand settings UI",
        "Pending",
        "Low",
        "5.3,4.5",
        16,
        2,
        None,
        0,
        "Frontend Engineer",
        date(2026, 8, 26),
        date(2026, 8, 28),
        None,
        "Admin can edit brand without redeploy (optional acceptance)",
        "Optional per master plan",
        "",
    ),
    (
        "5.6",
        "WP3 — Frontend Map + White-label",
        "WP3 verification + review stop",
        "Purpose: close white-label only when map + config branding acceptance criteria pass.\n"
        "Steps: verify ACs; PR; human review; do not mix WP5 on the same branch.",
        "Merged WP3",
        "Pending",
        "High",
        "5.1,5.4",
        8,
        1,
        None,
        0,
        "Engineering Lead",
        date(2026, 8, 28),
        date(2026, 8, 29),
        None,
        "All WP3 acceptance criteria pass",
        "",
        "",
    ),
    (
        "6.0",
        "WP4 — Backend/API Documentation",
        "WP4 kickoff (can parallel early)",
        "Purpose: start the backend architecture map as documentation-only, low-risk work.\n"
        "Steps: create wp-4-backend-map; prefer starting after WP2 so auth docs match reality; can begin after WP0 if staffed in parallel.",
        "Branch",
        "Pending",
        "Medium",
        "1.11",
        1,
        0.25,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 19),
        date(2026, 8, 19),
        None,
        "Docs branch ready",
        "Better after WP2 for accurate auth sections",
        "",
    ),
    (
        "6.1",
        "WP4 — Backend/API Documentation",
        "Router catalog (all endpoints)",
        "Purpose: catalogue every HTTP endpoint with method, path, models, auth requirement, and service/domain call.\n"
        "Steps: walk all routers; document consistently; update after WP2 auth lands.",
        "BACKEND_MAP.md routers section",
        "Pending",
        "Medium",
        "6.0",
        16,
        2,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 19),
        date(2026, 8, 21),
        None,
        "Every endpoint documented with auth + models",
        "",
        "",
    ),
    (
        "6.2",
        "WP4 — Backend/API Documentation",
        "Domain model + graph + data layer maps",
        "Purpose: document ObjectModel patterns, LangGraph flows, repository usage, migrations, and SurrealDB features in use.\n"
        "Steps: catalogue models/relationships; map each graph’s inputs/steps/outputs; explain repository call-site pattern and migrations.",
        "BACKEND_MAP.md domain/graphs/data",
        "Pending",
        "Medium",
        "6.1",
        16,
        2,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 21),
        date(2026, 8, 25),
        None,
        "Every domain model and graph documented",
        "",
        "",
    ),
    (
        "6.3",
        "WP4 — Backend/API Documentation",
        "Jobs, config/secrets, how-to playbooks",
        "Purpose: finish the operator/engineer map with jobs, env vars, and five how-to-add playbooks.\n"
        "Steps: document surreal-commands; env/secrets; playbooks for endpoint, model+migration, provider, job, source type; reconcile with existing change-playbooks.md.",
        "BACKEND_MAP.md complete",
        "Pending",
        "Medium",
        "6.2",
        12,
        1.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 8, 25),
        date(2026, 8, 26),
        None,
        "Five how-to playbooks present and accurate",
        "",
        "",
    ),
    (
        "6.4",
        "WP4 — Backend/API Documentation",
        "WP4 review stop",
        "Purpose: peer-review the map for accuracy and merge.\n"
        "Steps: review against live code; fix gaps; merge; confirm a new engineer can locate changes using only BACKEND_MAP.",
        "docs/BACKEND_MAP.md on main",
        "Pending",
        "Medium",
        "6.3",
        4,
        0.5,
        None,
        0,
        "Engineering Lead",
        date(2026, 8, 26),
        date(2026, 8, 27),
        None,
        "New engineer can locate changes using only this doc",
        "",
        "",
    ),
    (
        "7.0",
        "WP5 — External Source Connectors",
        "WP5 kickoff",
        "Purpose: design connectors that feed the existing ingestion pipeline instead of reinventing extraction.\n"
        "Steps: create wp-5-connectors; draft SourceConnector interface; confirm hard dependency on WP2 for per-user OAuth tokens.",
        "Branch + design note",
        "Pending",
        "High",
        "4.10",
        4,
        0.5,
        None,
        0,
        "Engineer",
        date(2026, 9, 1),
        date(2026, 9, 1),
        None,
        "Design reuses content-core + graphs/source.py",
        "Blocked until WP2 users/tokens exist",
        "",
    ),
    (
        "7.1",
        "WP5 — External Source Connectors",
        "SourceConnector interface + bulk job fan-out",
        "Purpose: one “add location” action becomes N document jobs with per-doc progress and partial failure tolerance.\n"
        "Steps: define authenticate/list_documents/fetch_document; extend source_commands for fan-out; ensure one bad file does not abort the batch.",
        "Connector API + bulk command",
        "Pending",
        "Critical",
        "7.0",
        24,
        3,
        None,
        0,
        "Backend Engineer",
        date(2026, 9, 1),
        date(2026, 9, 4),
        None,
        "Single failure does not abort batch; progress per document",
        "",
        "",
    ),
    (
        "7.2",
        "WP5 — External Source Connectors",
        "SharePoint connector (Microsoft Graph)",
        "Purpose: let an Entra-signed-in user pull an entire SharePoint folder into chat-able sources.\n"
        "Steps: OAuth on behalf of the user; least-privilege Sites/Files read scopes; enumerate folder; download supported files into existing ingestion; document admin consent.",
        "SharePointConnector",
        "Pending",
        "Critical",
        "7.1,4.7",
        32,
        4,
        None,
        0,
        "Backend Engineer",
        date(2026, 9, 4),
        date(2026, 9, 10),
        None,
        "User connects SharePoint, picks folder, pulls all supported docs",
        "",
        "",
    ),
    (
        "7.3",
        "WP5 — External Source Connectors",
        "Generic DMS / multi-doc link connector",
        "Purpose: support folder URLs / IDs that resolve to many documents, with an extension point for other DMS systems.\n"
        "Steps: implement base multi-doc connector; keep the SourceConnector interface as the only required surface for new connectors.",
        "Generic multi-doc connector",
        "Pending",
        "High",
        "7.1",
        16,
        2,
        None,
        0,
        "Backend Engineer",
        date(2026, 9, 8),
        date(2026, 9, 10),
        None,
        "New connector = implement interface only",
        "",
        "",
    ),
    (
        "7.4",
        "WP5 — External Source Connectors",
        "Encrypted per-user token storage",
        "Purpose: store connector OAuth tokens encrypted per user using existing encryption-key infrastructure.\n"
        "Steps: persist tokens encrypted; never share across users; respect source-system permissions (never fetch what the user cannot access).",
        "Encrypted token store",
        "Pending",
        "Critical",
        "7.2,2.8",
        12,
        1.5,
        None,
        0,
        "Backend Engineer",
        date(2026, 9, 10),
        date(2026, 9, 11),
        None,
        "Tokens encrypted per user; no cross-user leak",
        "",
        "",
    ),
    (
        "7.5",
        "WP5 — External Source Connectors",
        "Frontend: Add from SharePoint / Link flow",
        "Purpose: ship the operator UX for connect → folder pick → select → progress, then chat across the pulled set.\n"
        "Steps: add sources steps UI; show per-doc progress; ensure i18n for all locales; group pulled docs for chat/search.",
        "Sources UI flow",
        "Pending",
        "High",
        "7.2,7.3",
        24,
        3,
        None,
        0,
        "Frontend Engineer",
        date(2026, 9, 11),
        date(2026, 9, 16),
        None,
        "User can chat across the whole pulled set",
        "i18n required for all locales",
        "",
    ),
    (
        "7.6",
        "WP5 — External Source Connectors",
        "docs/CONNECTORS.md + WP5 review",
        "Purpose: document Entra scopes/consent and how to add a connector; close WP5 on acceptance criteria.\n"
        "Steps: write CONNECTORS.md; verify ACs; PR; human review stop.",
        "docs/CONNECTORS.md; merged WP5",
        "Pending",
        "High",
        "7.4,7.5",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 9, 16),
        date(2026, 9, 17),
        None,
        "All WP5 acceptance criteria pass",
        "",
        "",
    ),
    (
        "8.0",
        "WP6 — Doc Processing Benchmarks",
        "WP6 kickoff + enumerate supported types",
        "Purpose: list what content-core actually supports today and what needs work (OCR, EPUB, upload HTML, etc.).\n"
        "Steps: inventory from real code/config; note gaps; create wp-6-benchmarks. Can run after WP0; needs target hardware for later measurement tasks.",
        "Type inventory",
        "Pending",
        "Medium",
        "1.11",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 9, 1),
        date(2026, 9, 2),
        None,
        "Supported types documented from real code",
        "No guessed client-facing numbers",
        "",
    ),
    (
        "8.1",
        "WP6 — Doc Processing Benchmarks",
        "Build /benchmarks/ harness",
        "Purpose: produce repeatable measured metrics — not estimates — for ingestion, extraction, embedding, memory, and search/chat latency.\n"
        "Steps: build parameterized harness under /benchmarks/; output machine-readable reports.",
        "/benchmarks/ harness",
        "Pending",
        "High",
        "8.0",
        24,
        3,
        None,
        0,
        "Engineer",
        date(2026, 9, 2),
        date(2026, 9, 5),
        None,
        "Harness runs repeatably and outputs a metrics report",
        "",
        "",
    ),
    (
        "8.2",
        "WP6 — Doc Processing Benchmarks",
        "Assemble representative corpus",
        "Purpose: find empirical slowdown/failure points across sizes and types.\n"
        "Steps: assemble small/medium/large/very-large docs plus scanned PDF, audio, and web page; ensure corpus licensing is clean for redistribution in-repo if needed.",
        "Fixed corpus under benchmarks/",
        "Pending",
        "High",
        "8.1",
        12,
        1.5,
        None,
        0,
        "Engineer",
        date(2026, 9, 5),
        date(2026, 9, 8),
        None,
        "Corpus covers the size/type matrix",
        "",
        "",
    ),
    (
        "8.3",
        "WP6 — Doc Processing Benchmarks",
        "Define accuracy methodology",
        "Purpose: define how accuracy is measured so client claims are defensible.\n"
        "Steps: specify extraction fidelity, retrieval relevance (labeled Q&A), and chat groundedness methods; report per model tier.",
        "Accuracy method doc section",
        "Pending",
        "High",
        "8.1",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 9, 5),
        date(2026, 9, 8),
        None,
        "Accuracy reported as method + numbers",
        "",
        "",
    ),
    (
        "8.4",
        "WP6 — Doc Processing Benchmarks",
        "Run ≥2 hardware profiles",
        "Purpose: gather real numbers on bare-minimum and recommended hardware.\n"
        "Steps: run harness on both profiles; record figures; note local-model vs API-provider resource differences. Requires access to target hardware.",
        "Raw results JSON/CSV",
        "Pending",
        "Critical",
        "8.2,8.3",
        24,
        3,
        None,
        0,
        "Engineer",
        date(2026, 9, 8),
        date(2026, 9, 11),
        None,
        "Real measured numbers for both profiles",
        "Hardware access is a dependency",
        "",
    ),
    (
        "8.5",
        "WP6 — Doc Processing Benchmarks",
        "docs/PERFORMANCE_AND_SIZING.md + review",
        "Purpose: publish client-facing sizing guidance backed only by harness output.\n"
        "Steps: write types, limits, times, accuracy, min vs recommended hardware; peer review; merge.",
        "docs/PERFORMANCE_AND_SIZING.md",
        "Pending",
        "High",
        "8.4",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 9, 11),
        date(2026, 9, 12),
        None,
        "Doc contains measured numbers only",
        "",
        "",
    ),
    (
        "9.0",
        "WP7 — Cross-platform Packaging",
        "WP7 kickoff",
        "Purpose: package the real authenticated + branded app, not the pre-WP2 password prototype.\n"
        "Steps: create wp-7-packaging only after WP2 and WP3 are on main.",
        "Branch",
        "Pending",
        "High",
        "5.6,4.10",
        2,
        0.25,
        None,
        0,
        "Engineer",
        date(2026, 9, 18),
        date(2026, 9, 18),
        None,
        "Starts only after branded + authenticated app exists",
        "",
        "",
    ),
    (
        "9.1",
        "WP7 — Cross-platform Packaging",
        "Verify Docker Compose on Windows + Linux",
        "Purpose: make containers the recommended identical path on both OSes.\n"
        "Steps: verify docker-compose and Dockerfile.single on Docker Desktop/WSL2 and Linux; document as primary deploy path.",
        "Verified container deploy",
        "Pending",
        "Critical",
        "9.0",
        16,
        2,
        None,
        0,
        "DevOps / Engineer",
        date(2026, 9, 18),
        date(2026, 9, 22),
        None,
        "Container deployment verified on both OSes",
        "",
        "",
    ),
    (
        "9.2",
        "WP7 — Cross-platform Packaging",
        "Native Linux install path (systemd)",
        "Purpose: support customers who refuse containers.\n"
        "Steps: systemd units + install script; document dependencies for common distros; verify on at least one distro.",
        "Linux native docs + scripts",
        "Pending",
        "Medium",
        "9.1",
        16,
        2,
        None,
        0,
        "DevOps / Engineer",
        date(2026, 9, 22),
        date(2026, 9, 24),
        None,
        "Verified on ≥1 Linux distro",
        "",
        "",
    ),
    (
        "9.3",
        "WP7 — Cross-platform Packaging",
        "Native Windows Service path",
        "Purpose: support Windows Server native installs.\n"
        "Steps: Windows Service wrapper; SurrealDB-on-Windows notes; frontend serve docs; verify on Windows Server or equivalent.",
        "Windows native docs + scripts",
        "Pending",
        "Medium",
        "9.1",
        16,
        2,
        None,
        0,
        "DevOps / Engineer",
        date(2026, 9, 22),
        date(2026, 9, 24),
        None,
        "Verified on Windows Server or equivalent",
        "",
        "",
    ),
    (
        "9.4",
        "WP7 — Cross-platform Packaging",
        "Installer helper CLI (interactive + non-interactive)",
        "Purpose: let a non-expert stand up a branded client instance without hand-editing half a dozen files.\n"
        "Steps: CLI for prereq check → collect brand/Entra/provider/DB/encryption → write config → migrate → start → health check; add scripted/non-interactive mode for repeatable installs.",
        "onboard/install CLI",
        "Pending",
        "Critical",
        "9.1,5.4",
        32,
        4,
        None,
        0,
        "Backend Engineer",
        date(2026, 9, 24),
        date(2026, 9, 30),
        None,
        "Full install in both modes; scripted branded client stand-up works",
        "Deployment counterpart to WP3 theming",
        "",
    ),
    (
        "9.5",
        "WP7 — Cross-platform Packaging",
        "docs/DEPLOYMENT.md + WP7 review",
        "Purpose: one operator guide for container + native + CLI paths.\n"
        "Steps: write DEPLOYMENT.md; verify WP7 ACs; PR; human review.",
        "docs/DEPLOYMENT.md",
        "Pending",
        "High",
        "9.2,9.3,9.4",
        8,
        1,
        None,
        0,
        "Engineer",
        date(2026, 9, 30),
        date(2026, 10, 1),
        None,
        "All WP7 acceptance criteria pass",
        "",
        "",
    ),
    (
        "10.0",
        "WP8 — Onboarding & In-app Help",
        "WP8 kickoff (LAST)",
        "Purpose: build onboarding against final flows only — wizard/tour copy must match the shipped product.\n"
        "Steps: create wp-8-onboarding after WP2/3/5/7 are stable on main.",
        "Branch",
        "Pending",
        "Medium",
        "9.5,7.6,5.6",
        2,
        0.25,
        None,
        0,
        "Frontend Engineer",
        date(2026, 10, 2),
        date(2026, 10, 2),
        None,
        "Built against final UX",
        "Must be last in the program sequence",
        "",
    ),
    (
        "10.1",
        "WP8 — Onboarding & In-app Help",
        "First-run / admin setup wizard",
        "Purpose: take a fresh instance to a working configured app without tribal knowledge.\n"
        "Steps: detect fresh instance; guide providers/keys, models, brand (admin), connect a source, create first notebook; all copy via i18n.",
        "Setup wizard",
        "Pending",
        "High",
        "10.0",
        24,
        3,
        None,
        0,
        "Frontend Engineer",
        date(2026, 10, 2),
        date(2026, 10, 7),
        None,
        "Completing the wizard leaves a working configured app",
        "",
        "",
    ),
    (
        "10.2",
        "WP8 — Onboarding & In-app Help",
        "User guided tour (core loop)",
        "Purpose: teach the core loop — add source → search → chat → transform → podcast — with an accessible spotlight tour.\n"
        "Steps: implement dismissible/resumable tour; keep steps short; i18n all locales.",
        "Guided tour",
        "Pending",
        "High",
        "10.1",
        16,
        2,
        None,
        0,
        "Frontend Engineer",
        date(2026, 10, 7),
        date(2026, 10, 9),
        None,
        "New user can complete the core-loop tour",
        "",
        "",
    ),
    (
        "10.3",
        "WP8 — Onboarding & In-app Help",
        "Contextual tooltips + empty states + help surface",
        "Purpose: remove dead-ends for new users on every main screen.\n"
        "Steps: tooltips on non-obvious controls; useful empty states; persistent help (docs, shortcuts, restart tour, BrandConfig support URL); all strings in i18n.",
        "Tooltips/empty states/help",
        "Pending",
        "Medium",
        "10.2",
        20,
        2.5,
        None,
        0,
        "Frontend Engineer",
        date(2026, 10, 9),
        date(2026, 10, 14),
        None,
        "All copy in i18n; help reachable everywhere",
        "Locale parity required across all locales",
        "",
    ),
    (
        "10.4",
        "WP8 — Onboarding & In-app Help",
        "docs/ONBOARDING.md + program close review",
        "Purpose: document onboarding structure and verify program-level definition of done.\n"
        "Steps: write ONBOARDING.md; confirm a new client can be stood up by config + installer only (branded, Entra-auth’d, connectors, Windows/Linux) without per-client code rebuilds.",
        "docs/ONBOARDING.md; program DoD check",
        "Pending",
        "Medium",
        "10.3",
        8,
        1,
        None,
        0,
        "Engineering Lead",
        date(2026, 10, 14),
        date(2026, 10, 15),
        None,
        "All WP8 ACs + program definition of done satisfied",
        "",
        "",
    ),
]
